//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagazEntities1 : DbContext
    {
        public MagazEntities1()
            : base("name=MagazEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Corpus> Corpus { get; set; }
        public virtual DbSet<DDR> DDR { get; set; }
        public virtual DbSet<Memory> Memory { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<Ohlad> Ohlad { get; set; }
        public virtual DbSet<Ohlad_water> Ohlad_water { get; set; }
        public virtual DbSet<PowerBlock> PowerBlock { get; set; }
        public virtual DbSet<Processor> Processor { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sborka> Sborka { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Videocard> Videocard { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
