//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sborka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sborka()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID_sborka { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_processor { get; set; }
        public Nullable<int> ID_Motherboard { get; set; }
        public Nullable<int> ID_corpus { get; set; }
        public Nullable<int> ID_ohlad { get; set; }
        public Nullable<int> ID_ohlad_water { get; set; }
        public Nullable<int> ID_ddr { get; set; }
        public Nullable<int> ID_memory { get; set; }
        public Nullable<int> ID_powerblock { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_videocard { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
        public Nullable<bool> ZakazSborki { get; set; }
    
        public virtual Corpus Corpus { get; set; }
        public virtual DDR DDR { get; set; }
        public virtual Memory Memory { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual Ohlad Ohlad { get; set; }
        public virtual Ohlad_water Ohlad_water { get; set; }
        public virtual PowerBlock PowerBlock { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual Sborka Sborka1 { get; set; }
        public virtual Sborka Sborka2 { get; set; }
        public virtual User User { get; set; }
        public virtual Videocard Videocard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
